# Generated by Django 3.1.3 on 2021-04-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_useraccount_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
