# Generated by Django 3.1.3 on 2021-04-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
